sudo: required
import: comunica/travis-presets:yarn.yml@master
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - g++-4.9
install: CC=gcc-4.9 CXX=g++-4.9 yarn install --pure-lockfile
script:
  - yarn run integration
cache:
  apt: true
