sudo: required
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - g++-4.9
language: node_js
node_js:
 - "8"
 - "10"
 - "12"
before_install: yarn global add greenkeeper-lockfile@1
install: CC=gcc-4.9 CXX=g++-4.9 yarn install --pure-lockfile
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn run build
  - yarn run lint
  - yarn run integration
cache:
  yarn: true
  apt: true
  directories:
    - node_modules
